@api_HostAddress = http://localhost:5205

GET {{api_HostAddress}}/api/stock
Accept: application/json

###

POST {{api_HostAddress}}/api/stock

###

POST {{api_HostAddress}}/api/stock
Content-Type: application/json

{
  "symbol": "BLAT",
  "companyName": "Microsoft Corporation",
  "purchase": 420.50,
  "lastDiv": 0.75,
  "industry": "Software",
  "marketCap": 3100000000000
}

###

PUT {{api_HostAddress}}/api/stock/199
Content-Type: application/json

{
  "symbol": "NFT",
  "companyName": "BOB Corporation",
  "purchase": 237.99,
  "lastDiv": 4.75,
  "industry": "Software",
  "marketCap": 345345
}

###
DELETE {{api_HostAddress}}/api/stock/8
Accept: application/json

###
GET {{api_HostAddress}}/api/comment
Accept: application/json

###